export enum SlackIntegrationCheckResult {
  OK = "OK",
  INVALID_SLACK_URL = "INVALID_SLACK_URL",
  FORBIDDEN = "FORBIDDEN",
  SLACK_NOT_AVAILABLE = "SLACK_NOT_AVAILABLE",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  NOT_SET_UP = "NOT_SET_UP"
}
