export enum RecruiteeIntegrationCheckResult {
  OK = "OK",
  BAD_ACCESS_TOKEN = "BAD_ACCESS_TOKEN",
  BAD_COMPANY_DOMAIN = "BAD_COMPANY_DOMAIN",
  RECRUITEE_NOT_AVAILABLE = "RECRUITEE_NOT_AVAILABLE",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  NOT_SET_UP = "NOT_SET_UP"
}
